name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '32 15 3 10 4'  # This will run the workflow every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean test -X
      working-directory: ./
      
    - name: Run Cucumber tests
      run: mvn test  # Adjust based on your build tool

    - name: List target directory for debugging
      run: ls -R target/

    - name: Upload Cucumber Reports
      uses: actions/upload-artifact@v3
      with :
        name: cucumber-reports
        path: target/*


    #- name: Generate HTML report
     # run: mvn site  # If using Maven site plugin for reports
