name: Run Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install dependencies
      run: |
        # For Maven projects
        mvn install

    - name: Build with Maven
      run: mvn clean test -X
      working-directory: ./
      
    - name: Run Cucumber tests
      run: mvn test  # Adjust based on your build tool

    - name: Generate HTML report
      run: mvn site  # If using Maven site plugin for reports
